/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#633f00",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9fd",
        "on-primary-fixed": "#3d0024",
        "surface-container-high": "#e7e8ec",
        "tertiary-fixed-dim": "#ffb955",
        "primary": "#3f0025",
        "background": "#f8f9fd",
        "surface-container": "#edeef2",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d9dade",
        "on-background": "#191c1f",
        "outline-variant": "#c6c5d2",
        "secondary": "#1C2B6E",
        "outline": "#767681",
        "surface-tint": "#b60074",
        "inverse-primary": "#ffb0d0",
        "surface-variant": "#e1e2e6",
        "tertiary-fixed": "#ffddb4",
        "secondary-fixed-dim": "#b9c3ff",
        "surface-container-low": "#f2f3f7",
        "secondary-container": "#a4b2fd",
        "on-tertiary-fixed": "#291800",
        "surface": "#f8f9fd",
        "on-tertiary-container": "#d28b00",
        "secondary-fixed": "#dee1ff",
        "tertiary-container": "#472c00",
        "on-secondary-fixed": "#001258",
        "on-secondary-fixed-variant": "#334185",
        "inverse-on-surface": "#eff1f5",
        "on-primary-container": "#ff5bb0",
        "primary-fixed-dim": "#ffb0d0",
        "tertiary": "#F5A623",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2e3134",
        "error": "#ba1a1a",
        "on-secondary-container": "#344285",
        "surface-container-highest": "#e1e2e6",
        "on-surface-variant": "#454650",
        "on-error": "#ffffff",
        "on-surface": "#191c1f",
        "primary-container": "#65003e",
        "primary-fixed": "#ffd8e6",
        "on-primary-fixed-variant": "#8c0057"
      },
      fontFamily: {
        "headline": ["Poppins", "Plus Jakarta Sans"],
        "body": ["Nunito", "Be Vietnam Pro"],
        "label": ["Be Vietnam Pro"]
      },
    },
  },
  plugins: [],
}
